title: Spherical View Synthesis
description: for Self-Supervised 360<sup>o</sup> Depth Estimation
show_downloads: true
theme: jekyll-theme-architect

github:
  data_url: https://vcl3d.github.io/3D60/
  models_url: https://github.com/VCL3D/SphericalViewSynthesis/releases
  owner_url: https://zokin.github.io
  owner_name: Nikolaos Zioulis
